version: 1
validation: sovereign
account:
  name: radcoin
  address_prefix: rad
  chain_id: radcoin-1
  denom: urad
  binary: radcoind
accounts: 
- name: validator
  coins:
  - 10000000000urad
- name: foundation
  coins:
  - 30000000000urad
- name: community
  coins:
  - 25000000000urad
- name: publicsale
  coins:
  - 35000000000urad
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
- name: validator1
  bonded: 200000000stake
- name: validator2
  bonded: 100000000stake